### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by huangguabaizhan** [hotmanga/hotmanga#1]
sir，the web can't be used. please .
sir,   can you create a community we can exchange informations, like telegram or etc. 
thank you.

**Comment by hotmanga** [comment]
The New Web Site : https://www.manga2020.com


huangguabaizhan ***@***.***> 于2021年5月18日周二 10:01写道：

**Comment by hotmanga** [comment]
The New Web Site : https://www.manga2022.com/
